name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_version:
        - 1.0.0-root_v6.04.18
        - 1.0.0-root_v6.06.08
        - 1.0.0-root_v6.08.08
        - 1.0.0-root_v6.12.06
        - 1.0.0-root_v6.14.06
        - 1.0.0-root_v6.18.02
        - 1.0.0-root_v6.20.02
        - 1.0.0

    container: docker://gipert/bat:${{ matrix.container_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Build gerda-fitter executable
      working-directory: src
      run: make
    - name: Generate test data
      working-directory: test/data
      run: for f in *.C; do root -l -b -q -x $f; done
    - name: Run tests
      working-directory: test
      run: |
        for j in *.json; do
          echo "gerda-fitter $j"
          ../src/gerda-fitter $j;
        done

# vim: expandtab tabstop=2 shiftwidth=2
